baseurl: /road_to_heaven

title: "UDIT SRIVASTAVA"
author: "UDIT SRIVASTAVA"
bio-oneliner: "A Pythonista"

social-site:
    facebook: "www.facebook.com/uditsrivastava"
    instagram: ""
    twitter: ""
    github: ""
    
