baseurl: /road_to_heaven

title: "RAVITESH SRIVASTAVA"
author: "RAVITESH SRIVASTAVA"
bio-oneliner: "A Pythonista"

social-site:
    facebook: "www.facebook.com/raviteshsrivastava"
    instagram: ""
    twitter: ""
    github: ""
    
